version: "3.8"
services:
        apache:
                container_name: apache
                build: ./docker/apache
                links:
                  - php
                ports:
                  - "80:80"
        php:
                container_name: php
                build: ./docker/php
                ports:
                 - "9000:9000"
                volumes:
                 - ./src:/usr/local/apache2/htdocs
                working_dir: /usr/local/apache2/htdocs
        mysql:
            image: mysql:8.0.27
            container_name: mysql
            environment:
              MYSQL_ROOT_PASSWORD: 'pps'
              MYSQL_DATABASE: pps
              MYSQL_USER: pps
              MYSQL_PASSWORD: 'pps'
            ports:
              - "3306:3306"
            volumes:
              - ./database/mysql:/var/lib/mysql
        phpmyadmin:
            image: phpmyadmin/phpmyadmin
            container_name: pma
            links:
              - mysql
            environment:
              PMA_HOST: mysql
              PMA_PORT: 3306
              PMA_ARBITRARY: 1
            restart: always
            ports:
              - 8085:80
        mongo:
            image: mongo:5.0
            container_name: mongo
            environment:
                - MONGO_INITDB_ROOT_USERNAME=root
                - MONGO_INITDB_ROOT_PASSWORD=pps
            restart: unless-stopped
            ports:
              - "27017:27017"
            volumes:
              - ./database/mongodb/db:/data/db
              - ./database/mongodb/dev.archive:/Databases/dev.archive
              - ./database/mongodb/production:/Databases/production
        mongo-express:
            image: mongo-express
            container_name: mexpress
            environment:
              - ME_CONFIG_MONGODB_ADMINUSERNAME=root
              - ME_CONFIG_MONGODB_ADMINPASSWORD=pps
              - ME_CONFIG_MONGODB_URL=mongodb://root:pps@mongo:27017/?authSource=admin
              - ME_CONFIG_BASICAUTH_USERNAME=pps
              - ME_CONFIG_BASICAUTH_PASSWORD=pps
            links:
              - mongo
            restart: unless-stopped
            ports:
              - "8081:8081"
